# Generated by Django 3.1.7 on 2021-03-31 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0006_article_article_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_image',
            field=models.ImageField(null=True, upload_to='', verbose_name='Makaleye Fotograf ekleyin'),
        ),
    ]
